/// Flutter icons InvertoryIcon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InventoryIcon
///      fonts:
///       - asset: fonts/InventoryIcon.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class InventoryIcon {
  InventoryIcon._();

  static const String _kFontFam = 'InventoryIcon';

  static const IconData borderPurchaseList = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData borderInventory = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
}
