/// Flutter icons Menu_search
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Menu_search
///      fonts:
///       - asset: fonts/Menu_search.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class MenuSearchIcons {
  MenuSearchIcons._();

  static const String _kFontFam = 'Menu_search';

  static const IconData menuSearch = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fillOrderAddBtn = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData orderBorderAddBtn = IconData(
    0xe802,
    fontFamily: _kFontFam,
  );
}
