/// Flutter icons MenuIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuIcons
///      fonts:
///       - asset: fonts/MenuIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class MenuIcons {
  MenuIcons._();

  static const String _kFontFam = 'MenuIcons';
  static const IconData roundTable = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData menuPlaceholder = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
  static const IconData menuEmptyPlaceholder = IconData(
    0xe802,
    fontFamily: _kFontFam,
  );
  static const IconData checkList = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData servingTime = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData coookingTime = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData totalCookingTime = IconData(
    0xe806,
    fontFamily: _kFontFam,
  );
  static const IconData recipeBookIcon = IconData(
    0xe807,
    fontFamily: _kFontFam,
  );
  static const IconData recipe = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData recipeCookingBook = IconData(
    0xe809,
    fontFamily: _kFontFam,
  );
  static const IconData recipeBookmark = IconData(
    0xe80a,
    fontFamily: _kFontFam,
  );
  static const IconData recipeBookmarkOutline = IconData(
    0xe80b,
    fontFamily: _kFontFam,
  );
}
