/// Flutter icons Reservation
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Reservation
///      fonts:
///       - asset: fonts/Reservation.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ReservationIcons {
  ReservationIcons._();

  static const _kFontFam = 'Reservation';

  static const IconData booking = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData checkInDesk = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData hotelBell = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData noReservation = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData reserved = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData reservedCheckHolder = IconData(
    0xe805,
    fontFamily: _kFontFam,
  );
}
