import 'package:flutter/material.dart';

// final NavigationRoutes navigationRoutes = NavigationRoutes.getInstance();

final PageStorageBucket bucketGlobal = PageStorageBucket();

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>(
  debugLabel: 'navigatorKey',
);

// Define a list of language objects
List<Map<String, String>> jsonLanguagesData = <Map<String, String>>[
  <String, String>{'name': 'Afrikaans', 'code_2': 'af'},
  <String, String>{'name': 'Albanian', 'code_2': 'sq'},
  <String, String>{'name': 'Amharic', 'code_2': 'am'},
  <String, String>{'name': 'Arabic', 'code_2': 'ar'},
  <String, String>{'name': 'Armenian', 'code_2': 'hy'},
  <String, String>{'name': 'Assamese', 'code_2': 'as'},
  <String, String>{'name': 'Aymara', 'code_2': 'ay'},
  <String, String>{'name': 'Azerbaijani', 'code_2': 'az'},
  <String, String>{'name': 'Bambara', 'code_2': 'bm'},
  <String, String>{'name': 'Basque', 'code_2': 'eu'},
  <String, String>{'name': 'Belarusian', 'code_2': 'be'},
  <String, String>{'name': 'Bengali', 'code_2': 'bn'},
  <String, String>{'name': 'Bhojpuri', 'code_2': 'bho'},
  <String, String>{'name': 'Bosnian', 'code_2': 'bs'},
  <String, String>{'name': 'Bulgarian', 'code_2': 'bg'},
  <String, String>{'name': 'Catalan', 'code_2': 'ca'},
  <String, String>{'name': 'Cebuano', 'code_2': 'ceb'},
  <String, String>{'name': 'Chinese (Simplified)', 'code_2': 'zh-cn'},
  <String, String>{'name': 'Chinese (Traditional)', 'code_2': 'zh-tw'},
  <String, String>{'name': 'Corsican', 'code_2': 'co'},
  <String, String>{'name': 'Croatian', 'code_2': 'hr'},
  <String, String>{'name': 'Czech', 'code_2': 'cs'},
  <String, String>{'name': 'Danish', 'code_2': 'da'},
  <String, String>{'name': 'Dhivehi', 'code_2': 'dv'},
  <String, String>{'name': 'Dogri', 'code_2': 'doi'},
  <String, String>{'name': 'Dutch', 'code_2': 'nl'},
  <String, String>{'name': 'English', 'code_2': 'en'},
  <String, String>{'name': 'Esperanto', 'code_2': 'eo'},
  <String, String>{'name': 'Estonian', 'code_2': 'et'},
  <String, String>{'name': 'Ewe', 'code_2': 'ee'},
  <String, String>{'name': 'Filipino (Tagalog)', 'code_2': 'fil'},
  <String, String>{'name': 'Finnish', 'code_2': 'fi'},
  <String, String>{'name': 'French', 'code_2': 'fr'},
  <String, String>{'name': 'Frisian', 'code_2': 'fy'},
  <String, String>{'name': 'Galician', 'code_2': 'gl'},
  <String, String>{'name': 'Georgian', 'code_2': 'ka'},
  <String, String>{'name': 'German', 'code_2': 'de'},
  <String, String>{'name': 'Greek', 'code_2': 'el'},
  <String, String>{'name': 'Guarani', 'code_2': 'gn'},
  <String, String>{'name': 'Gujarati', 'code_2': 'gu'},
  <String, String>{'name': 'Haitian Creole', 'code_2': 'ht'},
  <String, String>{'name': 'Hausa', 'code_2': 'ha'},
  <String, String>{'name': 'Hawaiian', 'code_2': 'haw'},
  <String, String>{'name': 'Hebrew', 'code_2': 'he'},
  <String, String>{'name': 'Hindi', 'code_2': 'hi'},
  <String, String>{'name': 'Hmong', 'code_2': 'hmn'},
  <String, String>{'name': 'Hungarian', 'code_2': 'hu'},
  <String, String>{'name': 'Icelandic', 'code_2': 'is'},
  <String, String>{'name': 'Igbo', 'code_2': 'ig'},
  <String, String>{'name': 'Ilocano', 'code_2': 'ilo'},
  <String, String>{'name': 'Indonesian', 'code_2': 'id'},
  <String, String>{'name': 'Irish', 'code_2': 'ga'},
  <String, String>{'name': 'Italian', 'code_2': 'it'},
  <String, String>{'name': 'Japanese', 'code_2': 'ja'},
  <String, String>{'name': 'Javanese', 'code_2': 'jv'},
  <String, String>{'name': 'Kannada', 'code_2': 'kn'},
  <String, String>{'name': 'Kazakh', 'code_2': 'kk'},
  <String, String>{'name': 'Khmer', 'code_2': 'km'},
  <String, String>{'name': 'Kinyarwanda', 'code_2': 'rw'},
  <String, String>{'name': 'Konkani', 'code_2': 'gom'},
  <String, String>{'name': 'Korean', 'code_2': 'ko'},
  <String, String>{'name': 'Krio', 'code_2': 'kri'},
  <String, String>{'name': 'Kurdish (Kurmanji)', 'code_2': 'ku'},
  <String, String>{'name': 'Kurdish (Sorani)', 'code_2': 'ckb'},
  <String, String>{'name': 'Kyrgyz', 'code_2': 'ky'},
  <String, String>{'name': 'Lao', 'code_2': 'lo'},
  <String, String>{'name': 'Latin', 'code_2': 'la'},
  <String, String>{'name': 'Latvian', 'code_2': 'lv'},
  <String, String>{'name': 'Lingala', 'code_2': 'ln'},
  <String, String>{'name': 'Lithuanian', 'code_2': 'lt'},
  <String, String>{'name': 'Luganda', 'code_2': 'lg'},
  <String, String>{'name': 'Luxembourgish', 'code_2': 'lb'},
  <String, String>{'name': 'Macedonian', 'code_2': 'mk'},
  <String, String>{'name': 'Maithili', 'code_2': 'mai'},
  <String, String>{'name': 'Malagasy', 'code_2': 'mg'},
  <String, String>{'name': 'Malay', 'code_2': 'ms'},
  <String, String>{'name': 'Malayalam', 'code_2': 'ml'},
  <String, String>{'name': 'Maltese', 'code_2': 'mt'},
  <String, String>{'name': 'Maori', 'code_2': 'mi'},
  <String, String>{'name': 'Marathi', 'code_2': 'mr'},
  <String, String>{'name': 'Meiteilon (Manipuri)', 'code_2': 'mni-mtei'},
  <String, String>{'name': 'Mizo', 'code_2': 'lus'},
  <String, String>{'name': 'Mongolian', 'code_2': 'mn'},
  <String, String>{'name': 'Myanmar (Burmese)', 'code_2': 'my'},
  <String, String>{'name': 'Nepali', 'code_2': 'ne'},
  <String, String>{'name': 'Norwegian', 'code_2': 'no'},
  <String, String>{'name': 'Nyanja (Chichewa)', 'code_2': 'ny'},
  <String, String>{'name': 'Odia (Oriya)', 'code_2': 'or'},
  <String, String>{'name': 'Oromo', 'code_2': 'om'},
  <String, String>{'name': 'Pashto', 'code_2': 'ps'},
  <String, String>{'name': 'Persian', 'code_2': 'fa'},
  <String, String>{'name': 'Polish', 'code_2': 'pl'},
  <String, String>{'name': 'Portuguese', 'code_2': 'pt'},
  <String, String>{'name': 'Punjabi', 'code_2': 'pa'},
  <String, String>{'name': 'Quechua', 'code_2': 'qu'},
  <String, String>{'name': 'Romanian', 'code_2': 'ro'},
  <String, String>{'name': 'Russian', 'code_2': 'ru'},
  <String, String>{'name': 'Samoan', 'code_2': 'sm'},
  <String, String>{'name': 'Sanskrit', 'code_2': 'sa'},
  <String, String>{'name': 'Scots Gaelic', 'code_2': 'gd'},
  <String, String>{'name': 'Sepedi', 'code_2': 'nso'},
  <String, String>{'name': 'Serbian', 'code_2': 'sr'},
  <String, String>{'name': 'Sesotho', 'code_2': 'st'},
  <String, String>{'name': 'Shona', 'code_2': 'sn'},
  <String, String>{'name': 'Sindhi', 'code_2': 'sd'},
  <String, String>{'name': 'Sinhala', 'code_2': 'si'},
  <String, String>{'name': 'Slovak', 'code_2': 'sk'},
  <String, String>{'name': 'Slovenian', 'code_2': 'sl'},
  <String, String>{'name': 'Somali', 'code_2': 'so'},
  <String, String>{'name': 'Spanish', 'code_2': 'es'},
  <String, String>{'name': 'Sundanese', 'code_2': 'su'},
  <String, String>{'name': 'Swahili', 'code_2': 'sw'},
  <String, String>{'name': 'Swedish', 'code_2': 'sv'},
  <String, String>{'name': 'Tagalog (Filipino)', 'code_2': 'tl'},
  <String, String>{'name': 'Tajik', 'code_2': 'tg'},
  <String, String>{'name': 'Tamil', 'code_2': 'ta'},
  <String, String>{'name': 'Tatar', 'code_2': 'tt'},
  <String, String>{'name': 'Telugu', 'code_2': 'te'},
  <String, String>{'name': 'Thai', 'code_2': 'th'},
  <String, String>{'name': 'Tigrinya', 'code_2': 'ti'},
  <String, String>{'name': 'Tsonga', 'code_2': 'ts'},
  <String, String>{'name': 'Turkish', 'code_2': 'tr'},
  <String, String>{'name': 'Turkmen', 'code_2': 'tk'},
  <String, String>{'name': 'Twi (Akan)', 'code_2': 'ak'},
  <String, String>{'name': 'Ukrainian', 'code_2': 'uk'},
  <String, String>{'name': 'Urdu', 'code_2': 'ur'},
  <String, String>{'name': 'Uyghur', 'code_2': 'ug'},
  <String, String>{'name': 'Uzbek', 'code_2': 'uz'},
  <String, String>{'name': 'Vietnamese', 'code_2': 'vi'},
  <String, String>{'name': 'Welsh', 'code_2': 'cy'},
  <String, String>{'name': 'Xhosa', 'code_2': 'xh'},
  <String, String>{'name': 'Yiddish', 'code_2': 'yi'},
  <String, String>{'name': 'Yoruba', 'code_2': 'yo'},
  <String, String>{'name': 'Zulu', 'code_2': 'zu'},
];
